# ZTE BSP wgh modify for codec  begin
snd-soc-tlv320aic326x-objs := tlv320aic326x.o   tlv320aic326x_mini-dsp.o tlv320aic326x_minidsp_config.o aic326x_tiload.o
obj-$(CONFIG_SND_SOC_TLV320AIC326X)     += snd-soc-tlv320aic326x.o
# ZTE BSP wgh modify for codec  end